### ISSUE TITLE
🚑 !HOTFIX: App crashing on Android

### ISSUE THREAD

**Issue by isaaclkh** [Medithings/MediLight_App#35]
### 🚑 !HOTFIX: App crashing on Android

* Issue code:
  * I/flutter (27198): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:08.687464
E/AndroidRuntime(27198): FATAL EXCEPTION: main
E/AndroidRuntime(27198): Process: com.example.ble_uart, PID: 27198
E/AndroidRuntime(27198): android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=888) posted from package com.example.ble_uart, crashing app(uid=10407, pid=27198): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.example.ble_uart id=0x7f070060) visible user=0 )
E/AndroidRuntime(27198):        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2225)
E/AndroidRuntime(27198):        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime(27198):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
E/AndroidRuntime(27198):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27198):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(27198):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(27198):        at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(27198):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27198):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(27198):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/flutter (27306): `flutter_background_service_android` threw an error: Exception: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml
I/flutter (27306): Device Name Matched MEDiLight001
I/flutter (27306): Device Connected
I/flutter (27306): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:12.193502
I/flutter (27306): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:14.195554
I/flutter (27306): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:16.195378
I/flutter (27306): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:18.191941
I/flutter (27306): FLUTTER BACKGROUND SERVICE: 2023-11-09 20:20:20.192529
E/AndroidRuntime(27306): FATAL EXCEPTION: main
E/AndroidRuntime(27306): Process: com.example.ble_uart, PID: 27306
E/AndroidRuntime(27306): android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=888) posted from package com.example.ble_uart, crashing app(uid=10407, pid=27306): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.example.ble_uart id=0x7f070060) visible user=0 )
E/AndroidRuntime(27306):        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2225)
E/AndroidRuntime(27306):        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime(27306):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
E/AndroidRuntime(27306):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27306):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(27306):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(27306):        at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(27306):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27306):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(27306):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
* Don't know why

**Comment by isaaclkh** [comment]
Notification icon added (ic_bg_service_small)
